[toolchain]
url = "file:////home/btl/WBTL_SDK/ti/j722s/toolchain/arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-linux-gnu"
path = "arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-linux-gnu/bin"
name = "gcc"
version = "13.2.1"
system_name = "linux"
system_processor = "aarch64"
host = "aarch64-none-linux-gnu"
crosstool_prefix = "aarch64-none-linux-gnu-"
cc = "aarch64-none-linux-gnu-gcc"
cxx = "aarch64-none-linux-gnu-g++"
fc = "aarch64-none-linux-gnu-gfortran"
ld = "aarch64-none-linux-gnu-ld"
ranlib = "aarch64-none-linux-gnu-ranlib"
ar = "aarch64-none-linux-gnu-ar"
nm = "aarch64-none-linux-gnu-nm"
objdump = "aarch64-none-linux-gnu-objdump"
strip = "aaarch64-none-linux-gnu-strip"

[rootfs]
url = "file:////home/btl/WBTL_SDK/ti/j722s/targetfs/aarch64-linux-gnu"
path = "aarch64-linux-gnu"
pkg_config_path = ["usr/local/lib/pkgconfig"]
lib_dirs = ["usr/lib", "usr/local/lib"]